version: "3.8"

services:
  db:
    image: ubuntu/mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'tgbot123'
      MYSQL_DATABASE: 'tgbot'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  app:
    depends_on:
      - db
    #image: assist_bot:0.0.1
    build:
      context: .
      #dockerfile: Dockerfile
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/tgbot?allowPublicKeyRetrieval=true&useSSL=false"
    ports:
      - '8080:8080'